# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - release
  - devel
sudo: false
cache: packages

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'